version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PORT: 8080
    image: fullcycle-ddd-challenge/api:dev
    container_name: api
    restart: always
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
